In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.read_csv('WDICountry.csv')
df1.head()

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Unnamed: 30
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,Central Bureau of Statistics and Central Bank ...,Latin America & Caribbean,High income,AW,...,NaN,Enhanced General Data Dissemination System (e-...,2010,NaN,NaN,Yes,NaN,NaN,2016.0,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Central Statistics Organization; World Bank st...,South Asia,Low income,AF,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,IMF ; Source of population estimates: UN Popul...,Sub-Saharan Africa,Lower middle income,AO,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2017.0,NaN
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,Albanian Institute of Statistics ; Source of p...,Europe & Central Asia,Upper middle income,AL,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2017/18",Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2017.0,NaN
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,"Government of Andorra, Department of Statistic...",Europe & Central Asia,High income,AD,...,NaN,NaN,2011. Population data compiled from administra...,NaN,NaN,Yes,NaN,NaN,NaN,NaN

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 31 columns):
Country Code                                         263 non-null object
Short Name                                           263 non-null object
Table Name                                           263 non-null object
Long Name                                            263 non-null object
2-alpha code                                         261 non-null object
Currency Unit                                        217 non-null object
Special Notes                                        250 non-null object
Region                                               217 non-null object
Income Group                                         217 non-null object
WB-2 code                                            262 non-null object
National accounts base year                          206 non-null object
National accounts reference year                     69 non-null object
SNA price valuation                                  209 non-null object
Lending category                                     143 non-null object
Other groups                                         59 non-null object
System of National Accounts                          206 non-null object
Alternative conversion factor                        47 non-null object
PPP survey year                                      191 non-null object
Balance of Payments Manual in use                    195 non-null object
External debt Reporting status                       120 non-null object
System of trade                                      203 non-null object
Government Accounting concept                        158 non-null object
IMF data dissemination standard                      186 non-null object
Latest population census                             217 non-null object
Latest household survey                              152 non-null object
Source of most recent Income and expenditure data    168 non-null object
Vital registration complete                          118 non-null object
Latest agricultural census                           128 non-null object
Latest industrial data                               147 non-null float64
Latest trade data                                    246 non-null float64
Unnamed: 30                                          0 non-null float64
dtypes: float64(3), object(28)
memory usage: 63.8+ KB

In [4]:
df1.columns

Index(['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code',
       'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code',
       'National accounts base year', 'National accounts reference year',
       'SNA price valuation', 'Lending category', 'Other groups',
       'System of National Accounts', 'Alternative conversion factor',
       'PPP survey year', 'Balance of Payments Manual in use',
       'External debt Reporting status', 'System of trade',
       'Government Accounting concept', 'IMF data dissemination standard',
       'Latest population census', 'Latest household survey',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data', 'Unnamed: 30'],
      dtype='object')

In [5]:
df1[['Short Name', 'Income Group', 'External debt Reporting status', 'System of trade',
       'Government Accounting concept']]

,Short Name,Income Group,External debt Reporting status,System of trade,Government Accounting concept
0,Aruba,High income,NaN,General trade system,NaN
1,Afghanistan,Low income,Actual,General trade system,Consolidated central government
2,Angola,Lower middle income,Actual,Special trade system,Budgetary central government
3,Albania,Upper middle income,Actual,Special trade system,Consolidated central government
4,Andorra,High income,NaN,General trade system,NaN
...,...,...,...,...,...
258,Kosovo,Lower middle income,Actual,NaN,NaN
259,Yemen,Low income,Actual,Special trade system,NaN
260,South Africa,Upper middle income,Preliminary,General trade system,Consolidated central government
261,Zambia,Lower middle income,Actual,General trade system,Budgetary central government
262,Zimbabwe,Low income,Actual,General trade system,Budgetary central government

In [7]:
df2 = pd.read_csv('WDIData.csv')
df2

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 63
0,Arab World,ARB,"2005 PPP conversion factor, GDP (LCU per inter...",PA.NUS.PPP.05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"2005 PPP conversion factor, private consumptio...",PA.NUS.PRVT.PP.05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,82.407647,82.827636,83.169227,83.587141,83.954293,84.230630,84.570425,NaN,NaN,NaN
3,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,86.136134,86.782683,87.288244,88.389705,88.076774,88.517967,88.768654,NaN,NaN,NaN
4,Arab World,ARB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,74.543489,75.770972,76.772916,78.839139,77.487377,78.564439,78.958780,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422131,Zimbabwe,ZWE,Women who believe a husband is justified in be...,SG.VAW.NEGL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,21.400000,NaN,NaN,NaN,21.400000,NaN,NaN,NaN,NaN
422132,Zimbabwe,ZWE,Women who believe a husband is justified in be...,SG.VAW.REFU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,16.900000,NaN,NaN,NaN,14.500000,NaN,NaN,NaN,NaN
422133,Zimbabwe,ZWE,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.900000,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN
422134,Zimbabwe,ZWE,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.500000,NaN,NaN,33.500000,32.400000,NaN,NaN,NaN,NaN
422135,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,58.200000,58.400000,58.600000,58.800000,58.900000,58.900000,59.000000,59.1,NaN,NaN

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422136 entries, 0 to 422135
Data columns (total 64 columns):
Country Name      422136 non-null object
Country Code      422136 non-null object
Indicator Name    422136 non-null object
Indicator Code    422136 non-null object
1960              38296 non-null float64
1961              42017 non-null float64
1962              44198 non-null float64
1963              44084 non-null float64
1964              44611 non-null float64
1965              47305 non-null float64
1966              46902 non-null float64
1967              48633 non-null float64
1968              48209 non-null float64
1969              50011 non-null float64
1970              92892 non-null float64
1971              99126 non-null float64
1972              101898 non-null float64
1973              101523 non-null float64
1974              102838 non-null float64
1975              106739 non-null float64
1976              108656 non-null float64
1977              111988 non-null float64
1978              111568 non-null float64
1979              112371 non-null float64
1980              117218 non-null float64
1981              119130 non-null float64
1982              120334 non-null float64
1983              120112 non-null float64
1984              120914 non-null float64
1985              122087 non-null float64
1986              122924 non-null float64
1987              124326 non-null float64
1988              124043 non-null float64
1989              125804 non-null float64
1990              150283 non-null float64
1991              155342 non-null float64
1992              159292 non-null float64
1993              160651 non-null float64
1994              162800 non-null float64
1995              170546 non-null float64
1996              170804 non-null float64
1997              171881 non-null float64
1998              173814 non-null float64
1999              179128 non-null float64
2000              203655 non-null float64
2001              193654 non-null float64
2002              198571 non-null float64
2003              199394 non-null float64
2004              204796 non-null float64
2005              218727 non-null float64
2006              216489 non-null float64
2007              220471 non-null float64
2008              219495 non-null float64
2009              220308 non-null float64
2010              235880 non-null float64
2011              226320 non-null float64
2012              227731 non-null float64
2013              222939 non-null float64
2014              227702 non-null float64
2015              221790 non-null float64
2016              212990 non-null float64
2017              186601 non-null float64
2018              30247 non-null float64
Unnamed: 63       0 non-null float64
dtypes: float64(60), object(4)
memory usage: 206.1+ MB

In [9]:
df2.groupby('Country Code').count()

,Country Name,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 63
Country Code,,,,,,,,,,,,,,,,,,,,,
ABW,1599,1599,1599,87,88,90,88,88,91,88,...,483,440,432,423,408,375,366,257,13,0
AFG,1599,1599,1599,171,185,198,200,204,217,207,...,986,1008,994,954,994,999,935,933,130,0
AGO,1599,1599,1599,135,142,148,140,131,146,141,...,1146,1115,1010,1004,1051,1004,1003,866,134,0
ALB,1599,1599,1599,105,111,116,111,111,115,109,...,1158,1168,1225,1170,1144,1134,1064,1000,144,0
AND,1599,1599,1599,11,16,18,16,16,21,16,...,235,210,210,213,245,220,207,131,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XKX,1599,1599,1599,2,5,5,5,5,5,5,...,647,671,696,692,699,678,668,620,60,0
YEM,1599,1599,1599,112,123,129,124,128,135,129,...,1063,932,943,999,897,832,831,656,111,0
ZAF,1599,1599,1599,283,305,313,313,313,328,325,...,1220,1145,1134,1107,1186,1174,1116,990,186,0
ZMB,1599,1599,1599,137,152,159,160,192,227,244,...,1150,1046,1057,1056,1020,1018,959,915,138,0
ZWE,1599,1599,1599,142,164,162,169,196,228,218,...,1035,1138,1130,1017,1030,1042,999,893,126,0

In [10]:
len(df2['Indicator Name'].unique())

1599

In [11]:
df2.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', 'Unnamed: 63'],
      dtype='object')

In [23]:
df2 = df2[['Country Name',
     'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018']]

In [13]:
df3 = df2[['Country Name','Indicator Name',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018']]

In [24]:
test_df = df3[df3['Country Name'] == 'United States']

test_df.columns

test2 = test_df[['Indicator Name', '1960', '1961', '1962', '1963',
       '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972',
       '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981',
       '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990',
       '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018']].T



#https://www.geeksforgeeks.org/python-convert-two-lists-into-a-dictionary/


new_columns = list(test2.iloc[0].values)
old_columns = test2.columns
mapping = dict(zip(old_columns, new_columns)) 

test2 = test2.iloc[1:]
test2.rename(columns=mapping, inplace = True)
test2.head()

test2.index

country = "United States"
mapping2 = dict(zip(list(test2.index), list(map(lambda item: country+"_"+str(item),list(test2.index))))) 
mapping2

test2.rename(index=mapping2, inplace = True)
test2

,"2005 PPP conversion factor, GDP (LCU per international $)","2005 PPP conversion factor, private consumption (LCU per international $)",Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+),"Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)",...,"Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)",Women who believe a husband is justified in beating his wife (any of five reasons) (%),Women who believe a husband is justified in beating his wife when she argues with him (%),Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%)
United States_1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1990,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1991,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1992,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1993,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1994,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1995,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1996,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1997,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1998,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_1999,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2000,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2001,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2002,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2003,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2004,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2005,1,1,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2006,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2007,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2008,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2009,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2010,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2011,NaN,NaN,100,100,100,100,87.9579,84.0691,91.9819,90.7022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2012,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2013,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2014,NaN,NaN,100,100,100,100,93.5838,94.7977,92.3613,94.8355,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2015,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2016,NaN,NaN,100,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2017,NaN,NaN,NaN,NaN,NaN,NaN,93.1222,92.6862,93.5703,94.213,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States_2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
from datetime import datetime
#https://thispointer.com/python-how-to-get-current-date-and-time-or-timestamp/

In [16]:
dateTimeObj = datetime.now()
print(dateTimeObj)

countries = df3['Country Name'].unique()

data = pd.DataFrame(columns=list(test2.columns))

for country in countries:

    test_df = df3[df3['Country Name'] == country]
    test2 = test_df[test_df.columns[1:]].T

    new_columns = list(test2.iloc[0].values)
    old_columns = test2.columns
    mapping = dict(zip(old_columns, new_columns)) 

    test2 = test2.iloc[1:]
    test2.rename(columns=mapping, inplace = True)
    mapping2 = dict(zip(list(test2.index), list(map(lambda item: country+"_"+str(item),list(test2.index))))) 
    mapping2

    test2.rename(index=mapping2, inplace = True)
    data = pd.concat([data,test2], sort = False)

dateTimeObj2 = datetime.now()    
print(dateTimeObj2)

2019-11-30 18:30:20.569951
2019-11-30 18:32:50.515918

In [17]:
data.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 15576 entries, Arab World_1960 to Zimbabwe_2018
Data columns (total 1599 columns):
2005 PPP conversion factor, GDP (LCU per international $)                                                                                       184 non-null object
2005 PPP conversion factor, private consumption (LCU per international $)                                                                       184 non-null object
Access to clean fuels and technologies for cooking (% of population)                                                                            3995 non-null object
Access to electricity (% of population)                                                                                                         6958 non-null object
Access to electricity, rural (% of rural population)                                                                                            6271 non-null object
Access to electricity, urban (% of urban population)                                                                                            6959 non-null object
Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+)                                 491 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)                         491 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)                           491 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)                   491 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)                    482 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, primary education or less (% of population ages 15+)      490 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, richest 60% (% of population ages 15+)                    482 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, secondary education or more (% of population ages 15+)    490 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, young adults (% of population ages 15-24)                 491 non-null object
Adequacy of social insurance programs (% of total welfare of beneficiary households)                                                            263 non-null object
Adequacy of social protection and labor programs (% of total welfare of beneficiary households)                                                 281 non-null object
Adequacy of social safety net programs (% of total welfare of beneficiary households)                                                           247 non-null object
Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households)                                                       81 non-null object
Adjusted net enrollment rate, primary (% of primary school age children)                                                                        6121 non-null object
Adjusted net enrollment rate, primary, female (% of primary school age children)                                                                5504 non-null object
Adjusted net enrollment rate, primary, male (% of primary school age children)                                                                  5503 non-null object
Adjusted net national income (annual % growth)                                                                                                  6117 non-null object
Adjusted net national income (constant 2010 US$)                                                                                                6147 non-null object
Adjusted net national income (current US$)                                                                                                      8549 non-null object
Adjusted net national income per capita (annual % growth)                                                                                       6117 non-null object
Adjusted net national income per capita (constant 2010 US$)                                                                                     6147 non-null object
Adjusted net national income per capita (current US$)                                                                                           8546 non-null object
Adjusted net savings, excluding particulate emission damage (% of GNI)                                                                          6553 non-null object
Adjusted net savings, excluding particulate emission damage (current US$)                                                                       4914 non-null object
Adjusted net savings, including particulate emission damage (% of GNI)                                                                          4725 non-null object
Adjusted net savings, including particulate emission damage (current US$)                                                                       3574 non-null object
Adjusted savings: carbon dioxide damage (% of GNI)                                                                                              9854 non-null object
Adjusted savings: carbon dioxide damage (current US$)                                                                                           9058 non-null object
Adjusted savings: consumption of fixed capital (% of GNI)                                                                                       9876 non-null object
Adjusted savings: consumption of fixed capital (current US$)                                                                                    8136 non-null object
Adjusted savings: education expenditure (% of GNI)                                                                                              11606 non-null object
Adjusted savings: education expenditure (current US$)                                                                                           7627 non-null object
Adjusted savings: energy depletion (% of GNI)                                                                                                   9413 non-null object
Adjusted savings: energy depletion (current US$)                                                                                                8744 non-null object
Adjusted savings: gross savings (% of GNI)                                                                                                      6940 non-null object
Adjusted savings: mineral depletion (% of GNI)                                                                                                  10067 non-null object
Adjusted savings: mineral depletion (current US$)                                                                                               10416 non-null object
Adjusted savings: natural resources depletion (% of GNI)                                                                                        8798 non-null object
Adjusted savings: net forest depletion (% of GNI)                                                                                               9132 non-null object
Adjusted savings: net forest depletion (current US$)                                                                                            8099 non-null object
Adjusted savings: net national savings (% of GNI)                                                                                               6920 non-null object
Adjusted savings: net national savings (current US$)                                                                                            5276 non-null object
Adjusted savings: particulate emission damage (% of GNI)                                                                                        5932 non-null object
Adjusted savings: particulate emission damage (current US$)                                                                                     4788 non-null object
Adolescent fertility rate (births per 1,000 women ages 15-19)                                                                                   13920 non-null object
Adolescents out of school (% of lower secondary school age)                                                                                     3517 non-null object
Adolescents out of school, female (% of female lower secondary school age)                                                                      2921 non-null object
Adolescents out of school, male (% of male lower secondary school age)                                                                          2909 non-null object
Adults (ages 15+) and children (ages 0-14) newly infected with HIV                                                                              3621 non-null object
Adults (ages 15+) newly infected with HIV                                                                                                       3613 non-null object
Age dependency ratio (% of working-age population)                                                                                              13851 non-null object
Age dependency ratio, old (% of working-age population)                                                                                         13851 non-null object
Age dependency ratio, young (% of working-age population)                                                                                       13851 non-null object
Agricultural irrigated land (% of total agricultural land)                                                                                      856 non-null object
Agricultural land (% of land area)                                                                                                              13055 non-null object
Agricultural land (sq. km)                                                                                                                      13232 non-null object
Agricultural machinery, tractors                                                                                                                7783 non-null object
Agricultural machinery, tractors per 100 sq. km of arable land                                                                                  7444 non-null object
Agricultural methane emissions (% of total)                                                                                                     9715 non-null object
Agricultural methane emissions (thousand metric tons of CO2 equivalent)                                                                         10520 non-null object
Agricultural nitrous oxide emissions (% of total)                                                                                               9754 non-null object
Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)                                                                   10520 non-null object
Agricultural raw materials exports (% of merchandise exports)                                                                                   8586 non-null object
Agricultural raw materials imports (% of merchandise imports)                                                                                   8631 non-null object
Agriculture, forestry, and fishing, value added (% of GDP)                                                                                      9341 non-null object
Agriculture, forestry, and fishing, value added (annual % growth)                                                                               8548 non-null object
Agriculture, forestry, and fishing, value added (constant 2010 US$)                                                                             8609 non-null object
Agriculture, forestry, and fishing, value added (constant LCU)                                                                                  6934 non-null object
Agriculture, forestry, and fishing, value added (current LCU)                                                                                   7541 non-null object
Agriculture, forestry, and fishing, value added (current US$)                                                                                   9216 non-null object
Agriculture, forestry, and fishing, value added per worker (constant 2010 US$)                                                                  5268 non-null object
Air transport, freight (million ton-km)                                                                                                         8613 non-null object
Air transport, passengers carried                                                                                                               9010 non-null object
Air transport, registered carrier departures worldwide                                                                                          9003 non-null object
Alternative and nuclear energy (% of total energy use)                                                                                          8137 non-null object
Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)                                                                   565 non-null object
Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)                                                                      578 non-null object
Annual freshwater withdrawals, industry (% of total freshwater withdrawal)                                                                      561 non-null object
Annual freshwater withdrawals, total (% of internal resources)                                                                                  674 non-null object
Annual freshwater withdrawals, total (billion cubic meters)                                                                                     642 non-null object
Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)                               93 non-null object
Annualized average growth rate in per capita real survey mean consumption or income, total population (%)                                       93 non-null object
Antiretroviral therapy coverage (% of people living with HIV)                                                                                   3027 non-null object
Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)                                                                 958 non-null object
Aquaculture production (metric tons)                                                                                                            10880 non-null object
Arable land (% of land area)                                                                                                                    12918 non-null object
Arable land (hectares per person)                                                                                                               12892 non-null object
Arable land (hectares)                                                                                                                          10513 non-null object
ARI treatment (% of children under 5 taken to a health provider)                                                                                468 non-null object
Armed forces personnel (% of total labor force)                                                                                                 5763 non-null object
Armed forces personnel, total                                                                                                                   6172 non-null object
Arms exports (SIPRI trend indicator values)                                                                                                     2929 non-null object
Arms imports (SIPRI trend indicator values)                                                                                                     8253 non-null object
Automated teller machines (ATMs) (per 100,000 adults)                                                                                           2880 non-null object
Average grace period on new external debt commitments (years)                                                                                   6525 non-null object
Average grace period on new external debt commitments, official (years)                                                                         6525 non-null object
Average grace period on new external debt commitments, private (years)                                                                          6525 non-null object
Average grant element on new external debt commitments (%)                                                                                      6525 non-null object
Average grant element on new external debt commitments, official (%)                                                                            6525 non-null object
Average grant element on new external debt commitments, private (%)                                                                             6525 non-null object
Average interest on new external debt commitments (%)                                                                                           6525 non-null object
Average interest on new external debt commitments, official (%)                                                                                 6525 non-null object
Average interest on new external debt commitments, private (%)                                                                                  6525 non-null object
Average maturity on new external debt commitments (years)                                                                                       6525 non-null object
Average maturity on new external debt commitments, official (years)                                                                             6525 non-null object
Average maturity on new external debt commitments, private (years)                                                                              6525 non-null object
Average precipitation in depth (mm per year)                                                                                                    2068 non-null object
Average time to clear exports through customs (days)                                                                                            355 non-null object
Average transaction cost of sending remittances from a specific country (%)                                                                     253 non-null object
Average transaction cost of sending remittances to a specific country (%)                                                                       650 non-null object
Average working hours of children, study and work, ages 7-14 (hours per week)                                                                   132 non-null object
Average working hours of children, study and work, female, ages 7-14 (hours per week)                                                           132 non-null object
Average working hours of children, study and work, male, ages 7-14 (hours per week)                                                             132 non-null object
Average working hours of children, working only, ages 7-14 (hours per week)                                                                     126 non-null object

In [18]:
data.to_csv('Pre-Processed_data.csv', index = True)

#When passing it into data frame, be careful with the index because it is as a column, unless you want it like that.

In [19]:
data = pd.read_csv('Pre-Processed_data.csv')

In [22]:
data.head(200)

,Unnamed: 0,"2005 PPP conversion factor, GDP (LCU per international $)","2005 PPP conversion factor, private consumption (LCU per international $)",Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+),"Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)",...,"Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)",Women who believe a husband is justified in beating his wife (any of five reasons) (%),Women who believe a husband is justified in beating his wife when she argues with him (%),Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%)
0,Arab World_1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World_1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World_1962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World_1963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World_1964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Early-demographic dividend_1978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,Early-demographic dividend_1979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,Early-demographic dividend_1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,Early-demographic dividend_1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,Early-demographic dividend_1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN